# Generated by Django 5.0.7 on 2024-10-31 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'advice',
                'verbose_name_plural': 'advices',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('expirience_needed', models.CharField(max_length=10, verbose_name='experience_needed')),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'reward',
                'verbose_name_plural': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='Source_Of_Infection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('image', models.ImageField(upload_to='')),
                ('coordinates', models.CharField(max_length=100, verbose_name='coordinates')),
                ('risk', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], max_length=1)),
            ],
            options={
                'verbose_name': 'source_of_infection',
                'verbose_name_plural': 'source_of_infections',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('is_consumable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
            options={
                'verbose_name': 'type_task',
                'verbose_name_plural': 'type_tasks',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('expirience', models.CharField(max_length=10, verbose_name='experience')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.level')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.event')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.reward')),
            ],
            options={
                'verbose_name': 'challenge',
                'verbose_name_plural': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.reward')),
            ],
            options={
                'verbose_name': 'advertising',
                'verbose_name_plural': 'advertisings',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.challenge')),
                ('type_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.typetask')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
