# Generated by Django 5.0.7 on 2024-10-31 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.advertising')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.player')),
            ],
            options={
                'verbose_name': 'advertising_player',
                'verbose_name_plural': 'advertising_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='advertising',
            field=models.ManyToManyField(blank=True, through='preventify.Advertising_Player', to='preventify.advertising'),
        ),
    ]
