# Generated by Django 5.0.7 on 2024-10-31 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventify', '0002_advertising_player_player_advertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.player')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.task')),
            ],
            options={
                'verbose_name': 'task_player',
                'verbose_name_plural': 'task_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='task',
            field=models.ManyToManyField(blank=True, through='preventify.Task_Player', to='preventify.task'),
        ),
        migrations.CreateModel(
            name='Token_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.player')),
                ('tokens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.token')),
            ],
            options={
                'verbose_name': 'token_player',
                'verbose_name_plural': 'token_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.ManyToManyField(blank=True, through='preventify.Token_Player', to='preventify.token'),
        ),
    ]
