# Generated by Django 5.0.7 on 2024-10-31 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventify', '0003_task_player_player_task_token_player_player_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateTimeField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.player')),
            ],
            options={
                'verbose_name': 'badge_player',
                'verbose_name_plural': 'badge_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='badge',
            field=models.ManyToManyField(blank=True, through='preventify.Badge_Player', to='preventify.badge'),
        ),
        migrations.CreateModel(
            name='Event_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.player')),
            ],
            options={
                'verbose_name': 'event_player',
                'verbose_name_plural': 'event_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.ManyToManyField(blank=True, through='preventify.Event_Player', to='preventify.event'),
        ),
        migrations.CreateModel(
            name='Source_Of_Infection_Task_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_infection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.source_of_infection')),
                ('taskplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.task_player')),
            ],
            options={
                'verbose_name': 'source_of_infection_task_player',
                'verbose_name_plural': 'source_of_infection_task_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='source_of_infection',
            name='task_player',
            field=models.ManyToManyField(blank=True, through='preventify.Source_Of_Infection_Task_Player', to='preventify.task_player'),
        ),
        migrations.CreateModel(
            name='Token_Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.reward')),
                ('tokens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.token')),
            ],
            options={
                'verbose_name': 'token_reward',
                'verbose_name_plural': 'token_rewards',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='token',
            name='reward',
            field=models.ManyToManyField(blank=True, through='preventify.Token_Reward', to='preventify.reward'),
        ),
    ]
