# Generated by Django 5.0.7 on 2024-10-31 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventify', '0004_badge_player_player_badge_event_player_player_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertising_Player',
            new_name='AdvertisingPlayer',
        ),
        migrations.RenameModel(
            old_name='Badge_Player',
            new_name='BadgePlayer',
        ),
        migrations.RenameModel(
            old_name='Event_Player',
            new_name='EventPlayer',
        ),
        migrations.RenameModel(
            old_name='Token_Player',
            new_name='TokenPlayer',
        ),
        migrations.RenameModel(
            old_name='Token_Reward',
            new_name='TokenReward',
        ),
        migrations.RenameModel(
            old_name='Source_Of_Infection_Task_Player',
            new_name='SourceOfInfectionTaskPlayer',
        ),
        migrations.RenameModel(
            old_name='Task_Player',
            new_name='TaskPlayer',
        ),
        migrations.CreateModel(
            name='SourceOfInfection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('image', models.ImageField(upload_to='')),
                ('coordinates', models.CharField(max_length=100, verbose_name='coordinates')),
                ('risk', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], max_length=1)),
                ('task_player', models.ManyToManyField(blank=True, through='preventify.SourceOfInfectionTaskPlayer', to='preventify.taskplayer')),
            ],
            options={
                'verbose_name': 'source_of_infection',
                'verbose_name_plural': 'source_of_infections',
            },
        ),
        migrations.AlterField(
            model_name='sourceofinfectiontaskplayer',
            name='source_of_infection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventify.sourceofinfection'),
        ),
        migrations.DeleteModel(
            name='Source_Of_Infection',
        ),
    ]
