from . import admin_player
from . import admin_badge
from . import admin_token
from . import admin_reward
from . import admin_advertising
from . import admin_level
from . import admin_task
from . import admin_advice
from . import admin_badge_player
from . import admin_advertising_player