from . import resources_player
from . import resources_level
from . import resources_badge
from . import resources_token
from . import resources_advertising
from . import resources_reward
from . import resources_task
from . import resources_advice
from . import resources_badge_player
from . import resources_advertising_player