from . import models_player
from . import models_level
from . import models_badge
from . import models_source_of_infection
from . import models_token
from . import models_reward
from . import models_challenge
from . import models_event
from . import models_advertising
from . import models_task
from . import models_advice
from . import models_type_task
from .models_token_player import TokenPlayer
from .models_advertising_player import AdvertisingPlayer
from .models_task_player import TaskPlayer
from .models_source_of_infection_task_player import SourceOfInfectionTaskPlayer
from .models_event_player import EventPlayer
from .models_badge_player import BadgePlayer
from .models_token_reward import TokenReward